---- DATA PREPARATION AND UNDERSTANDING
	
	SELECT * FROM Cust
    SELECT * FROM prod_cat_info
    SELECT * FROM Transactions


   ---1. What is the total number of rows in each of the 3 tables in the database? 
        SELECT COUNT(*) FROM Cust
        SELECT COUNT(*) FROM prod_cat_info
        SELECT COUNT(*) FROM Transactions

   ---2. What is the total number of transactions that have a return? 
	    SELECT COUNT(total_amt) FROM Transactions
	    WHERE total_amt LIKE '-%'

   ---3. As you would have noticed, the dates provided across the datasets are not in correct format. As first steps, pls convert the date variables into valid date formats 
   ---  before proceeding ahead.
        SELECT CONVERT(DATE, DOB, 103) AS DATES FROM Cust
	    SELECT CONVERT(DATE, tran_date, 103) AS trans_date FROM Transactions

   ---4. What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns. 
        SELECT DATEDIFF(DAY, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))) AS Days , 
        DATEDIFF(MONTH, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105))) AS Months ,  
        DATEDIFF(YEAR, MIN(CONVERT(DATE, tran_date, 105)), MAX(CONVERT(DATE, tran_date, 105)))  AS Years
        FROM Transactions


   ---5. Which product category does the sub-category “DIY” belong to? 
        SELECT prod_cat
        FROM prod_cat_info
        WHERE prod_subcat LIKE 'DIY'


	--- DATA ANALYSIS


   ---1. Which channel is most frequently used for transactions? 
        SELECT TOP 1 
        Store_type, COUNT(transaction_id) Count_
        FROM Transactions
        GROUP BY Store_type
        ORDER BY COUNT(transaction_id) DESC

   ---2. What is the count of Male and Female customers in the database?
        SELECT Gender, COUNT(customer_Id) AS COUNTG 
		FROM Cust
		WHERE Gender IN ('F','M')
		GROUP BY Gender

   ---3. From which city do we have the maximum number of customers and how many?
		SELECT TOP 1 city_code,
		COUNT(customer_id) Cust_cnt
		FROM Cust
		GROUP BY city_code
		ORDER BY Cust_cnt DESC

   ---4. How many sub-categories are there under the Books category? 
        SELECT COUNT(prod_subcat) AS SUBCAT_CNT
		FROM prod_cat_info
		WHERE prod_cat = 'Books'
		GROUP BY prod_cat

   ---5. What is the maximum quantity of products ever ordered? 
	    SELECT TOP 1 QTY
		FROM Transactions
		ORDER BY Qty DESC

   ---6. What is the net total revenue generated in categories Electronics and Books?
        SELECT SUM(total_amt) Total_Revenue
		FROM Transactions
		WHERE prod_cat_cde IN (3 , 5)
		
   ---7. How many customers have >10 transactions with us, excluding returns? 
        SELECT COUNT(customer_Id) AS CUSTOMER_COUNT
		FROM Cust WHERE customer_Id IN 
		(
		SELECT cust_id
		FROM Transactions
		LEFT JOIN Cust ON customer_Id = cust_id
		WHERE total_amt NOT LIKE '-%'
		GROUP BY cust_id
		HAVING COUNT(transaction_id) > 10
		)
		 
   ---8. What is the combined revenue earned from the "Electronics" & "Clothing" categories from "Flagship store"?
        SELECT SUM(total_amt) AS Combined_Revenue
		FROM Transactions
		INNER JOIN prod_cat_info ON prod_cat_cde = prod_cat_code
		      AND  prod_subcat_cde = prod_subcat_code
		WHERE prod_cat IN ('Electronics' , 'Clothing') AND Store_type = 'Flagship store'

   ---9. What is the total revenue generated from "Male" customers in "Electronics" category? Output should display total revenue by prod sub-cat.
		SELECT prod_subcat , SUM(total_amt) AS Revenue
		FROM Transactions
		LEFT JOIN Cust ON cust_id = customer_Id
		LEFT JOIN prod_cat_info ON prod_subcat_cde = prod_subcat_code AND prod_cat_cde = prod_cat_code
		WHERE prod_cat_code = '3' AND GENDER = 'M'
		GROUP BY prod_subcat_code, prod_subcat

   ---10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
		 SELECT TOP 5 prod_subcat, 
		 (SUM(total_amt)/(SELECT SUM(total_amt) FROM Transactions)) * 100 AS Percent_of_sales,
		 (COUNT(CASE WHEN Qty < 0  THEN Qty ELSE NULL END)/SUM(Qty)) * 100 AS Percent_of_return
		 FROM Transactions
		 INNER JOIN prod_cat_info ON prod_cat_cde = prod_cat_code AND prod_subcat_cde = prod_subcat_code
		 GROUP BY prod_subcat
		 ORDER BY SUM(total_amt) DESC

   ---11. For all customers aged between 25 to 30 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max 
         --transaction date available in the data?
		 SELECT cust_id, SUM(total_amt) AS Total_revenue
		 FROM Transactions
		 WHERE cust_id IN
		 (SELECT customer_id 
		 FROM Cust
		 WHERE DATEDIFF (YEAR, CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
		 AND CONVERT(DATE,tran_date,103) BETWEEN  DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,tran_date,103))  FROM Transactions))
		 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
		 GROUP BY cust_id

   ---12. Which product category has seen the max value of returns in the last 3 months of transactions?
         SELECT TOP 1 prod_cat, SUM(total_amt) Value_return
		 FROM Transactions T1
		 INNER JOIN prod_cat_info T2 ON T1.prod_cat_cde = T2.prod_cat_code 
		 AND T1.prod_subcat_cde = T2.prod_subcat_code
		 WHERE total_amt < 0 
		 AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions))
		 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM Transactions)
		 GROUP BY prod_cat
		 
   ---13. Which store-type sells the maximum products; by value of sales amount and by quantity sold?
		 SELECT Store_type, 
		 SUM(Qty) t_qty,
		 SUM(total_amt) t_sales
		 FROM Transactions
		 GROUP BY Store_type
		 HAVING SUM(Qty) >= ALL (SELECT SUM(Qty) FROM Transactions GROUP BY Store_type)
		 AND SUM(total_amt) >= ALL (SELECT SUM(total_amt) FROM Transactions GROUP BY Store_type)

   ---14. What are the categories for which average revenue is above the overall average.
		 SELECT prod_cat, 
		 AVG(total_amt) AS Avg_rev
		 FROM Transactions
		 INNER JOIN prod_cat_info ON prod_cat_cde = prod_cat_code  AND  prod_subcat_cde = prod_subcat_code
		 GROUP BY prod_cat
		 HAVING AVG(total_amt) > (SELECT AVG(total_amt) FROM Transactions)
		 
   ---15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
         SELECT TOP 5 prod_cat, prod_subcat,
		 AVG(total_amt) AS Avg_Revenue,
		 SUM(total_amt) AS Revenue
		 FROM Transactions
		 INNER JOIN prod_cat_info ON prod_cat_cde = prod_cat_code  AND  prod_subcat_cde = prod_subcat_code
		 WHERE prod_cat IN
		 (
		 SELECT TOP 5
		 prod_cat
		 FROM Transactions
		 INNER JOIN prod_cat_info ON prod_cat_cde = prod_cat_code  AND  prod_subcat_cde = prod_subcat_code
		 GROUP BY prod_cat
		 ORDER BY SUM(Qty) DESC
		 )
		 GROUP BY prod_cat, prod_subcat


		