--- SQL CASESTUDY CAR SHOWROOM

SELECT * FROM cars
SELECT * FROM salespersons
SELECT * FROM sales

--Q1. What are the details of all cars purchased in the year 2022?

     SELECT c.*
	 FROM cars c
	 JOIN sales s ON c.car_id = s.car_id
	 WHERE YEAR(purchase_date) = 2022



--Q2. What is the total number of cars sold by each salesperson?

     SELECT sp.salesman_id, sp.name, COUNT(*) AS total_cars_sold
	 FROM salespersons sp
	 JOIN sales s ON sp.salesman_id = s.salesman_id
	 GROUP BY sp.salesman_id, sp.name;



--Q3. What is the total revenue generated by each salesperson?

	 SELECT sp.salesman_id, sp.name, SUM(c.cost_$) AS total_revenue
	 FROM salespersons sp
	 JOIN sales s ON sp.salesman_id = s.salesman_id
	 JOIN cars c ON s.car_id = c.car_id
	 GROUP BY sp.salesman_id, sp.name;



--Q4. What are the details of the cars sold by each salesperson?

	 SELECT sp.name AS salesperson_name, c.*
	 FROM salespersons sp
	 JOIN sales s ON sp.salesman_id = s.salesman_id
	 JOIN cars c ON s.car_id = c.car_id;



--Q5. What is the total revenue generated by each car type?

	 SELECT c.type, SUM(c.cost_$) AS total_revenue
	 FROM cars c
	 JOIN sales s ON c.car_id = s.car_id
	 GROUP BY c.type



--Q6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

	 SELECT c.*
	 FROM cars c
	 JOIN sales s ON c.car_id = s.car_id
	 JOIN salespersons sp ON s.salesman_id = sp.salesman_id
	 WHERE sp.name = 'Emily Wong' AND YEAR(s.purchase_date) = 2021;



--Q7. What is the total revenue generated by the sales of hatchback cars?

	 SELECT SUM(c.cost_$) AS total_revenue
	 FROM cars c
	 JOIN sales s ON c.car_id = s.car_id
	 WHERE c.style = 'Hatchback'; 



--Q.8 What is the total revenue generated by the sales of SUV cars in the year 2022?

	 SELECT SUM(c.cost_$) AS total_revenue
	 FROM cars c
	 JOIN sales s ON c.car_id = s.car_id
	 WHERE c.style = 'SUV' AND YEAR(s.purchase_date) = 2022;



--Q9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

	 SELECT sp.name, sp.city, COUNT(*) AS total_cars_sold
	 FROM salespersons AS sp
	 JOIN sales s ON sp.salesman_id = s.salesman_id
	 WHERE YEAR(s.purchase_date) = 2023
	 GROUP BY sp.name, sp.city
	 ORDER BY total_cars_sold DESC;



--Q10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

	 SELECT sp.name, sp.age
	 FROM salespersons sp
	 JOIN sales s ON sp.salesman_id = s.salesman_id
	 JOIN cars c ON s.car_id = c.car_id
	 WHERE YEAR(s.purchase_date) = 2022
	 GROUP BY sp.name, sp.age
	 ORDER BY SUM(c.cost_$) DESC;
	 
